class FontCaskaydiaCoveNerdFont < Formula
  version "2.3.0"
  sha256 "417c3e57a1185bcd432592fa7e1c182ac2ccd559e79ba25a5f7778ee346206f8"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/CascadiaCode.zip"
  desc "CaskaydiaCove Nerd Font (Cascadia Code)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Bold Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Bold.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete ExtraLight Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete ExtraLight.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Light Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Light.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Bold Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Bold.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono ExtraLight Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono ExtraLight.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Light Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Light.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono Regular.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono SemiBold Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono SemiBold.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono SemiLight Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Mono SemiLight.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete Regular.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete SemiBold Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete SemiBold.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete SemiLight Italic.otf"
    (share/"fonts").install "Caskaydia Cove Nerd Font Complete SemiLight.otf"
  end
  test do
  end
end
