class FontOverpassNerdFont < Formula
  version "2.2.2"
  sha256 "c40e71a8369eb1bd8ccfce217074f6b684594c22835290638136a974314ebc4f"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Overpass.zip"
  desc "Overpass Nerd Font families (Overpass)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Overpass Bold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Bold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Bold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraBold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraBold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraLight Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraLight Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraLight Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraLight Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Heavy Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Heavy Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Heavy Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Heavy Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Light Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Light Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Light Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono Bold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono Light Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Regular Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono Regular Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono SemiBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono SemiBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Regular Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Regular Nerd Font Complete.otf"
    (share/"fonts").install "Overpass SemiBold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass SemiBold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass SemiBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass SemiBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Thin Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Thin Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Thin Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Thin Nerd Font Complete.otf"
  end
  test do
  end
end
