class FontHasklugNerdFont < Formula
  version "2.3.2"
  sha256 "79e6d3ce2b343cd47030a759da33ecf0448b97b8069181dc9f8910b6a8444a1d"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Hasklig.zip"
  desc "Hasklug Nerd Font (Hasklig)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Hasklug Black Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Black Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Black Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Black Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Bold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Bold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Bold Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug ExtraLight Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug ExtraLight Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug ExtraLight Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug ExtraLight Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Light Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Light Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Light Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Medium Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Medium Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Medium Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Medium Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Semibold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Semibold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Semibold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Semibold Nerd Font Complete.otf"
  end
  test do
  end
end
