class FontImWritingNerdFont < Formula
  version "2.2.2"
  sha256 "3852130a129dc8b5146744015b468f7e4ba29c00c9a9f0b2b61cabc3316b7c9c"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/iA-Writer.zip"
  desc "IMWriting Nerd Font families (iA Writer)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "iM Writing Duo S Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duo S Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duo S Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duo S Bold Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duo S Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duo S Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duo S Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duo S Regular Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duospace Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "iM Writing Duospace Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duospace Bold Nerd Font Complete.otf"
    (share/"fonts").install "iM Writing Duospace Bold Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duospace BoldItalic Nerd Font Complete Mono.otf"
    (share/"fonts").install "iM Writing Duospace BoldItalic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duospace BoldItalic Nerd Font Complete.otf"
    (share/"fonts").install "iM Writing Duospace BoldItalic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duospace Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "iM Writing Duospace Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duospace Italic Nerd Font Complete.otf"
    (share/"fonts").install "iM Writing Duospace Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Duospace Regular Nerd Font Complete Mono.otf"
    (share/"fonts").install "iM Writing Duospace Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Duospace Regular Nerd Font Complete.otf"
    (share/"fonts").install "iM Writing Duospace Regular Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Mono S Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Mono S Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Mono S Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Mono S Bold Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Mono S Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Mono S Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Mono S Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Mono S Regular Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Quattro S Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Quattro S Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Quattro S Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Quattro S Bold Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Quattro S Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Quattro S Italic Nerd Font Complete.ttf"
    (share/"fonts").install "iM Writing Quattro S Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "iM Writing Quattro S Regular Nerd Font Complete.ttf"
  end
  test do
  end
end
