class FontJetbrainsMonoNerdFont < Formula
  version "2.3.0"
  sha256 "12c75a1eb7909460b53f203f160cbcf7315cc2805930511c4fe0901e5c48dc90"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/JetBrainsMono.zip"
  desc "JetBrainsMono Nerd Font families (JetBrains Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "JetBrains Mono Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Bold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Light Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Medium Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Regular Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Regular Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Thin Nerd Font Complete.ttf"
  end
  test do
  end
end
