name: Ruby
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Configure git
      run: |
        git config user.email 'action@github.com'
        git config user.name 'GitHub Actions'
    - name: Convert and commit
      run: |
        git submodule update --init --remote
        gem install bundler
        bundle config set --local without 'development'
        bundle install --jobs 4 --retry 3
        bundle exec ruby cask2formula convert
        bundle exec ruby cask2formula commit
    - name: Clean Formula directory
      run: |
        comm -23 --nocheck-order <(ls -1 Formula) <(ls -1 homebrew-cask-fonts/Casks) | xargs -I{} sh -c 'git rm ./Formula/{} && git commit -m "Remove {}"'
    - name: Publish to GitHub
      env:
        TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git push https://${TOKEN}@github.com/mxalbert1996/homebrew-fonts HEAD:master
